version: '3.7'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
        - "80:80"
        - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        links:
            - php-fpm
    php-fpm:
        build: 
            context: ./
            dockerfile: docker/php-fpm/php-fpm.docker
        container_name: php-fpm
        volumes:
            - ./:/var/www
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=appdb
            - MYSQL_USER=appuser
            - MYSQL_PASSWORD=apppwd
        volumes:
            - ./docker/mysql:/var/lib/mysql

