version: '3.7'
services:
    web:
        image: nginx:latest
        container_name: nginx
        ports:
        - "80:80"
        - "443:443"
        volumes:
            - ./app:/var/www
            - ./containers/nginx/conf:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
        links:
            - php-fpm
    php-fpm:
        build: 
            context: ./containers/php
            dockerfile: Dockerfile
        container_name: php-fpm
        volumes:
            - ./app:/var/www
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=appdb
            - MYSQL_USER=appuser
            - MYSQL_PASSWORD=apppwd
        volumes:
            - ./containers/mysql/conf:/etc/mysql
            - ./data:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
